name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'Server/**'
          frontend:
            - 'testHackathon_frontEnd/**'

    # run only if 'backend' files were changed
    - name: backend
      uses: appleboy/ssh-action@master
      if: steps.filter.outputs.backend == 'true'
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        passphrase: ${{ secrets.SERVER_PASSPHRASE }}
        script: |
          rm -rf /root/test/
          mkdir /root/test/
          cd /root/test/
          sudo git init
          sudo git clone https://github.com/andrzahar/test-hackathon-voronezh
          sudo docker compose -f /root/test/test-hackathon-voronezh/Server/docker-compose.yml up -d --force-recreate --no-deps --build

    # run only if 'frontend' files were changed
    - name: frontend
      uses: appleboy/ssh-action@master
      if: steps.filter.outputs.frontend == 'true'
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        passphrase: ${{ secrets.SERVER_PASSPHRASE }}
        script: |
          rm -rf /root/test/
          mkdir /root/test/
          cd /root/test/
          sudo git init
          sudo git clone https://github.com/andrzahar/test-hackathon-voronezh
          sudo docker compose -f /root/test/test-hackathon-voronezh/testHackathon_frontEnd/docker-compose.yml up -d --force-recreate --no-deps --build
