name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Run deploy on server"
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        passphrase: ${{ secrets.SERVER_PASSPHRASE }}
        script: |
          sudo git --git-dir /root/test-hackathon-voronezh/.git/ pull
          sudo docker compose -f /root/test-hackathon-voronezh/test-hackathon-voronezh/testHackathon_frontEnd/docker-compose.yml up -d
          sudo docker compose -f /root/test-hackathon-voronezh/test-hackathon-voronezh/Server/docker-compose.yml up -d
